(source gnu)
(source melpa)
(source marmalade)
(source org)

(depends-on "flx-ido")
(depends-on "ido-ubiquitous")
(depends-on "pallet")
(depends-on "req-package")
(depends-on "smart-mode-line")
(depends-on "zenburn-theme")